num1=int(input("enter the first number: "))
num2=int(input("enter the second number: "))
print("summation:",(num1+num2))
print("difference:",(num1-num2))
print("product:",(num1*num2))
print("quoitent:",(num1/num2))
print("exponent:",(num1**num2))
print("positive floor dividion:",(num1//num2))
print("negative floor dicision:",(-num1//num2))