#write a python program to read s employee name, designation, salary,special allowances,bonus as input from the user
empname=str(input("enter the employe name:"))
designation=str(input("enter the designation:"))
salary=int(input("enter the salary:"))
specialallowances=int(input("enter the special allowances:"))
bonus=int(input("enter the bonus:"))
print(empname)
print(designation)
print(salary)
print(specialallowances)
print(bonus)
grossmonthsalary=(salary+specialallowances)
print(grossmonthsalary)
g=(salary*12)
print(g)